name = "LegendOpticalFits"
uuid = "bbb9fcaf-2b60-4c6b-9c8a-4fdd17999abf"
version = "0.2.0"

[deps]
BAT = "c0cd4b16-88b7-57fa-983b-ab80aecada7e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HeterogeneousComputing = "2182be2a-124f-4a91-8389-f06db5907a21"
LegendDataManagement = "9feedd95-f0e0-423f-a8dc-de0970eae6b3"
LegendHDF5IO = "c9265ca6-b027-5446-b1a4-febfa8dd10b0"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
LegendOpticalFitsPlotsExt = ["Plots"]

[compat]
BAT = "4.0.3"
CSV = "0.10.15"
DensityInterface = "0.4.0"
Distributions = "0.25.120"
HDF5 = "0.17.2"
HeterogeneousComputing = "0.2.4"
LegendDataManagement = "0.5.6"
LegendHDF5IO = "0.1.17"
MLDataDevices = "1.12.0"
Pkg = "1.10"
Plots = "1.41.1"
Random = "1.10"
StatsBase = "0.34.6"
Tables = "1.12.1"
TypedTables = "1.4.6"
Unitful = "1.25.0"
ValueShapes = "0.11.3"
julia = "1.10"
